### PR TITLE
Update pipeline to point frontstage at services directly

### PR DESCRIPTION
**Pull request by jcox-dev**
This is for the changes in frontstage to be merged in by https://github.com/ONSdigital/ras-frontstage/pull/333.

### CODE REVIEW

**Comment by jcox-dev** [comment]
[[TBL] Have frontstage call the other services directly](https://trello.com/c/rxYfcnBR/113-tbl-have-frontstage-call-the-other-services-directly)

**Review by gavinleeedwards — APPROVED** [review]

**Review by liamtoozer — APPROVED** [review]

**Comment by jcox-dev** [comment]
As @benjefferies mentioned, we should incrementally deprecate the API service to avoid compounded issues with "greening" the pipeline following the changes for this.

**Comment by benjefferies** [comment]
If we add the frontstage api back in we can merge this now

**Comment by jcox-dev** [comment]
@benjefferies done in https://github.com/ONSdigital/ras-deploy/pull/13/commits/850315729bdff27c8c4f7a7284ffbf0fdf033e58

**Review by benjefferies — APPROVED** [review]

**Comment by benjefferies** [comment]
Pipeline is still green after deploying it. Need to merge https://github.com/ONSdigital/ras-frontstage/pull/333 when appropriate and hopefully it stays green

**Pull request merged**
