### PR TITLE
Initial concurrency dashboard

### PR DESCRIPTION
**Pull request by gemmai95**
A quick starting point to visualising current tested concurrency for RAS RM.

To view: http://concurrency-dashboard.apps.prunes.cf2.onsclofo.uk/

### CODE REVIEW

**Comment by gemmai95** [comment]
[Visibility of concurrency values](https://trello.com/c/QFOi2mDq/29-visibility-of-concurrency-values)

**Review by benjefferies — COMMENTED** [review]
As it's just a single html page have you considered just using git pages instead of deploying to CF?

**Review by tej99 — APPROVED** [review]
Changes look good 👍

**Review by andrewmil — APPROVED** [review]
Dashboard looks good :+1:

**Review by benjefferies — APPROVED** [review]

**Pull request merged**
